Azure/notation-azure-kv

- .github/workflows/release.yml
- .goreleaser.yml
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
Changes are based off github.com/deislabs/ratify 
Sample release can be found here 
https://github.com/sajayantony/notation-azure-kv/releases/tag/untagged-6851f22ba197c4a88dc6
> Added workflows for github release

- .github/workflows/workflow.yml
- .golangci.yml
- Makefile
- cmd/notation-azure-kv/sign.go
- cmd/notation-azure-kv/verify.go
- hack/go-install.sh
- pkg/sign/types.go
- pkg/verify/types.go
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- Adds workflow for running lint on codebase
- Adds workflow for running unit tests
> ci: add gh workflow for lint and unit test

- docs/nv2-sign-verify-aks.md
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Update docs to reflect released builds

- docs/nv2-sign-verify-aks.md
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
- Fix download instruction for pre-release notation and some markdown linting.
> Update docs to use pre-release of notation

- README.md
- cleanup.sh
- docs/nv2-bicep.md
- docs/nv2-sign-verify-aks.md
- iac/acr.bicep
- iac/aks.bicep
- iac/keyvault.bicep
- iac/main.bicep
- setup.sh
- Adds support to deploy all resources using Azure Bicep
- Adds support to call `./setup.sh` script for quick and easy deployment / signing of container images using Gatekeeper, Ratify, and Notation
> Add Bicep Support and easy setup.sh script for deployment

- docs/nv2-sign-verify-aks.md
> Update ratify article

- internal/version/version.go
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
> fix:fix version number

- internal/cloud/keyvault.go
- internal/version/version.go
1. Update version to `v0.4.0-alpha.3`
2. Update auth mode
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
> fix:fix version number and auth mode

- internal/version/version.go
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
> chore: bump up version to alpha.4

- go.mod
- go.sum
- internal/version/version.go
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
> upgrade the notation-go and notation-core-go version

- internal/version/version.go
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
> update the version to v0.5.0-rc.1

- internal/crypto/cert.go
> fix: pem cert chain parsing issue

- internal/crypto/cert.go
- internal/signature/signer.go
> feat: complete cert chain by `certbundle` plugin config

- internal/crypto/cert.go
> fix: add self-signed cert validation

- .github/workflows/release.yml
- .goreleaser.yml
Update gorelease configuration to be aligned with Notation
Resolves #64 
> feat: align release assets

- cmd/notation-azure-kv/key.go
- cmd/notation-azure-kv/main.go
- cmd/notation-azure-kv/metadata.go
- cmd/notation-azure-kv/metadata_test.go
- cmd/notation-azure-kv/sign.go
- internal/keyvault/keyvault.go
- internal/keyvault/keyvault_test.go
- refactored for unit test
- get metadata unit test
- keyvault package unit test
Resolve part of #66 
> test: add keyvault & get metadata unit test

- .github/workflows/workflow.yml
- README.md
> test: add code coverage

- .github/.codecov.yml
- .github/workflows/workflow.yml
> ci: update workflow to trigger when pushing commit to main

- .github/workflows/workflow.yml
- .gitignore
- Makefile
> fix: update Makefile test

- .github/.codecov.yml
- .github/workflows/release.yml
- Notation.Plugin.AzureKeyVault/Command/GetPluginMetadata.cs
- Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj
- Notation.Plugin.AzureKeyVault/Program.cs
- scripts/release.sh
Feature:
- added release script for .NET project
- update CI to trigger release script
Example release: https://github.com/JeyJeyGao/notation-azure-kv/releases/tag/untagged-f7b59db6549c8908c202
Resolves #95 
> ci: add .NET release CI

- docs/ca-signed-workflow.md
> doc: add openssl generated certificate

- Notation.Plugin.AzureKeyVault/Program.cs
> fix: update Notation brand name

- .github/.codecov.yml
> ci: set codecov target

- RELEASE_CHECKLIST.md
- scripts/release.sh
> ci: update release ci runtime name & add release checklist

- README.md
> doc: update artifact version in readme

- README.md
> doc: update version for README

- README.md
> doc: add macOS codesign

- README.md
- RELEASE_CHECKLIST.md
Update:
- updated version to v1.0.0-rc.2
- removed macOS codesign step in README.md
- update release check list to include the step for updating version in README.me
> doc: update for v1.0.0-rc.2

- README.md
> doc: release v1.0.0-rc.3

- .github/workflows/test.yml
- docs/ca-signed-workflow.md
- docs/plugin-config.md
- docs/self-signed-workflow.md
Update:
- doc quote NOTE format
- CI linter setting to avoid checking markdown file
> doc: update quote note

- Notation.Plugin.AzureKeyVault/Program.cs
Fix:
- update the link to `plugin-extensibility.md` to be v1.0.0
Resolves #128 
> fix: update help doc

- README.md
> doc: update readme for v1.0.1

- README.md
> doc: update README for v1.1.0

- Notation.Plugin.AzureKeyVault.Tests/ProgramTests.cs
- Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj
Bump:
- update Azure.Identity v1.12.0
Fix:
- fixed the error message for test as the library changed the error message
> bump: Azure.Identity 1.12.0

- README.md
- Updated v1.2.1 installation guide.
- Formatted README to pass [super-linter](https://github.com/super-linter/super-linter)
> docs: update README for v1.2.1
