Azure/notation-azure-kv

internal/cloud/keyvault.go
Add Managed Identity auth mode.
The default auth mode will be Azure CLI.
Set the below environment variable will switch to MI mode.
```
export AKV_AUTH_METHOD="AKV_AUTH_FROM_MI"
```
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
=> fix:fix akv not work in azure vm

cmd/notation-azure-kv/sign.go, internal/cloud/keyvault.go, internal/crypto/cert.go, internal/signature/signer.go
Removed unnessary error message wrapping.
Previous error returned:
>failed to sign payload: failed to build a certificate chain using certificates fetched from AKV with error: failed to validate certificate chain. error: x509: certificate signed by unknown authority. Try again with a certificate bundle file (including intermediate and root certificates) in PEM format through pluginConfig with `ca_certs` as key name and file path as value
Current error returned:
> failed to build a certificate chain using certificates fetched from AKV because x509: certificate signed by unknown authority. Try again with a certificate bundle file (including intermediate and root certificates) in PEM format through pluginConfig with `ca_certs` as key name and file path as value
For those error message …
=> fix: update error message

.github/workflows/release.yml, .github/workflows/workflow.yml, go.mod
=> build: update go version 1.20

cmd/notation-azure-kv/key.go, cmd/notation-azure-kv/main.go, cmd/notation-azure-kv/metadata.go, cmd/notation-azure-kv/sign.go, go.mod, go.sum
=> feat: remove urfave cli framework

README.md
=> doc: update scripts

Notation.Plugin.AzureKeyVault.Tests/ProgramTests.cs, Notation.Plugin.AzureKeyVault/Program.cs
Fix:
- before the fixing, the plugin needs to read the input before check the command name
- after the fixing, the plugin check the command name before reading the input
=> fix: check command before read input

Notation.Plugin.AzureKeyVault.Tests/Certificate/CertificateChainTests.cs, Notation.Plugin.AzureKeyVault/Certificate/CertificateChain.cs
After the PR, the plugin will not check the certificate chain integrity.
Resolves #116 
=> fix: remove X509Chain.Build to avoid compatibility issue

docs/ca-signed-workflow.md
Update:
- With the removal of the automatic certificate chain arrangement feature in update #116, you'll now need to manually create a valid certificate bundle by following the guide.
=> doc: update ca signed workflow

Notation.Plugin.AzureKeyVault.Tests/Certificate/CertificateBundleTests.cs, Notation.Plugin.AzureKeyVault.Tests/Command/GenerateSignatureTests.cs, Notation.Plugin.AzureKeyVault/Certificate/CertificateBundle.cs, Notation.Plugin.AzureKeyVault/Command/GenerateSignature.cs, docs/ca-signed-workflow.md, docs/self-signed-workflow.md
Feat:
- added self_signed parameter in the pluginConfig for self-signed certificate (`Certificates Get` permission)
Fix:
- removed as_secert pluginConfig
- secerts get is the default behavior when `self_signed` and `ca_certs` are not set (`Secrets Get` permission)
- added a message to remind user to enable secrets get permission
- raise exception when the ca_certs is empty
Parameters logic:
- self_signed is true && ca_certs=/path/to/cacerts **==>** exception
- self_signed is true && ca_certs is null or empty **==>** get self-signed certificate with `Certificates Get` permission
- self_signed is false or not set && ca_certs=/path/to/cacerts **==>** get leaf certificate with `Certificates Get` permission and read the certificate bundle from file
- self_signed is false or not set && ca_certs …
=> feat: add self_signed pluginConfig

scripts/build.sh
Fix:
- update tarball structure to remove the `./`
Tested the release pipeline on forked repo:
Resolves #127 
=> ci: update tarball structure

docs/ca-signed-workflow.md
The guide environment is local comand line with az logined admin account. We need certificate create and get permission to create the certificate and get the key id. However, for production deployment, customer should use managed identity or service principal instead of admin account, which will be mentioned in Microsoft Learn official document.
Resolves #132 
=> doc: update set policy

.github/workflows/test.yml, Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj, test/e2e/containerized/Dockerfile.mariner, test/e2e/containerized/test.sh
test:
- added containerized azure-kv plugin E2E test based on mcr.microsoft.com/cbl-mariner/base/core:2.0
fix:
- set InvariantGlobalization mode to avoid access culture-specific data, which removes the dependency of icu-libs (not contained in mariner image)
=> fix&test(e2e): mariner containerized e2e test

Notation.Plugin.AzureKeyVault/Program.cs
Improve the error message:
Previous:
```
notation sign notationreg.azurecr.io/hello-app:v2 --plugin azure-kv --id https://acrci-test-kv.vault.azure.net/keys/self-signed-pkcs13/70747b2064c0488e936eba7a29acc4c6
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v2) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Error: describe-key command failed: failed to execute the describe-key command for plugin azure-kv: ERROR: A certificate with (name/id) self-signed-pkcs13/versions/70747b2064c0488e936eba7a29acc4c6 was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see …
```
=> fix: improve RequestFailedException error message

Notation.Plugin.AzureKeyVault.Tests/ProgramTests.cs, Notation.Plugin.AzureKeyVault/Program.cs
=> test: add unit test for RequestFailedException

README.md, RELEASE_CHECKLIST.md
=> docs: update README for v1.0.2

.github/workflows/release.yml, .github/workflows/test.yml
=> bump(ci): update ci actions

.github/workflows/release.yml, .github/workflows/test.yml
Fix:
- added check for `e2e-mariner-container` test to only run on PR from this repo
- enabled override for `actions/upload-artifact@v4`, which is a breaking change in v4
=> fix(ci): test and release pipeline

Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj
Fix:
- dependabot was blocked by exception in Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj
Error log: https://github.com/Azure/notation-azure-kv/network/updates/815374970
=> fix: dependabot exception when parsing .csproj

Notation.Plugin.AzureKeyVault.Tests/KeyVault/CredentialsTests.cs, Notation.Plugin.AzureKeyVault.Tests/KeyVault/KeyVaultClientTests.cs, Notation.Plugin.AzureKeyVault/KeyVault/Credentials.cs, docs/plugin-config.md
Fix:
- removed `default` credential type
=> fix: update credential type logic

Notation.Plugin.AzureKeyVault.Tests/Command/GenerateSignatureTests.cs, Notation.Plugin.AzureKeyVault.Tests/KeyVault/KeyVaultClientTests.cs, Notation.Plugin.AzureKeyVault/Command/DescribeKey.cs, Notation.Plugin.AzureKeyVault/Command/GenerateSignature.cs, Notation.Plugin.AzureKeyVault/KeyVault/KeyVaultClient.cs, docs/ca-signed-workflow.md, docs/self-signed-workflow.md, test/e2e/action.yml
Feat:
- added versionless key/certificate identifier support
Test:
- added unit test
- added E2E test
Docs:
- added tips for versionless id feature
- fixed NOTE marks
Resolves #180 #178 
=> feat: add versionless key identifier support

README.md
=> doc: update readme for v1.2.0

.github/workflows/release.yml, .github/workflows/test.yml, Notation.Plugin.AzureKeyVault.Tests/ProgramTests.cs
Background: as the default `ubuntu-latest` runner [has upgraded](https://github.com/actions/runner-images/commit/976232da217887825e7541c2635bf39cbbf22654) to `ubuntu-24.04`, we need to ensure compatibility with older OS versions if we release the binary on a new runner as the dotnet building process depends on OS libraries (for example, `GLIBC`). 
CI:
- Unit test pipeline
- added unit test on Linux arm64 and windows x64.
- E2E pipeline
- built `linux-x64` binary on `ubuntu-24.04` and tested on `ubuntu-22.04`, `ubuntu-24.04` and `mcr.microsoft.com/cbl-mariner/base/core:2.0` container.
- built `linux-arm64` binary on `ubuntu-24.04-arm` and tested on `ubuntu-24.04-arm`, `ubuntu-22.04-arm`.
- built `windows-x64` binary on `windows-2022` and tested on `windows-2022` and `windows-2025` (GA).
- …
=> ci: improve reliability

.github/workflows/test.yml
This PR fixes some small typos on the names of the pipeline.
=> ci: fix pipeline name typos
